### ISSUE TITLE
Export issue in Python 2

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/famplex#26]
Encoding needs to be standardized in this export script to fix this:
```
Traceback (most recent call last):
  File "export/obo.py", line 116, in <module>
    save_obo_terms(obo_terms, 'bioentities.obo')
  File "export/obo.py", line 110, in save_obo_terms
    obo_str = term.to_obo()
  File "export/obo.py", line 29, in to_obo
    obo_str += 'synonym: "%s" %s []\n' % (synonym.name, synonym.status)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 14: ordinal not in range(128)
```

**Comment by bgyori** [comment]
This script has since been made Python 3-only (and exits with an appropriate message when run from Python 3) so the issue is not relevant anymore.
